feat: jsonrpc integration & c++ autocomplete
delta/codecharacter-lsp-2023 pull request #5
Opened 2023-02-18 07:01 UTC by vigneshd332

# Integrate JSONPRC

Integrates JSONRPC request handling with the LSP servers.

## Changes/Features/Bug Fixes

- [x] Integrate JSONRPC
- [x] Integrate C++ Language Server

2023-03-05 19:07 UTC, Ashwin125 requested changes

2023-03-05 19:07 UTC, Ashwin125 commented on controllers/jsonrpc.go
> +	if err != nil {
return err

2023-03-05 19:07 UTC, Ashwin125 commented on servers/servers.go
> +		// case models.Python:
Remove comment

2023-03-05 19:30 UTC, Ram-20062003 commented
update .env.example with `FRONTEND_URL`

2023-03-05 19:55 UTC, Ashwin125 approved these changes

2023-03-06 13:21 UTC, Ram-20062003 approved these changes

2023-03-06 13:24 UTC, merged